### ISSUE TITLE
Infografia de la realidad aumentada

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-EdwinOrtiz1412#1]
[Infografia de Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-EdwinOrtiz1412/files/14212678/Infografia.de.Realidad.aumentada.pdf)

**Comment by magaly1311** [comment]
Falta referencias 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
